image:
  - Visual Studio 2015
  # - ubuntu

# Defaults to MSBuild
build: off

clone_folder: c:\gopath\src\github.com\adamdecaf\cert-manage

environment:
  GOPATH: c:\gopath

stack: go 1.10, docker

services:
  - docker

test_script:
  - go vet ./...
  - go fmt ./...
  - CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o bin/cert-manage-amd64.exe github.com/adamdecaf/cert-manage
  - CGO_ENABLED=0 go test -test.parallel 8 ./...
  - INTEGRATION=yes go test -test.parallel 8 ./... -run TestIntegration__ -count 1
