image:
  - Visual Studio 2015
  # - ubuntu

# Defaults to MSBuild
build: off

clone_folder: c:\gopath\src\github.com\adamdecaf\cert-manage

environment:
  GOPATH: c:\gopath
  CGO_ENABLED: '1'
  GOOS: windows
  GOARCH: amd64
  DEBUG: true

stack: go 1.10, docker

services:
  - docker

test_script:
  - go vet ./...
  - go fmt ./...
  - go build -o bin/cert-manage-amd64.exe github.com/adamdecaf/cert-manage
  - go test -test.parallel 8 ./...
