language: go
sudo: required

os:
  - linux
  - osx

go:
  - 1.9.x
  - master

osx_image: xcode9.1

matrix:
  allow_failures:
    - go: master
  fast_finish: true
  exclude:
    - os: osx
      go: master
  include:
    - os: linux
      go: go1.10rc1

script:
  - make ci

services:
  - docker
