language: go
sudo: required

os:
  - linux
  - osx

go:
  - "1.10"

osx_image: xcode9.1

matrix:
  fast_finish: true
  include:
    - os: linux
      go: master

script:
  - make test

services:
  - docker
