language: go
sudo: required

os:
  - linux
  - osx

go:
  - 1.9.x

osx_image: xcode9.1

matrix:
  fast_finish: true
  exclude:
    - os: osx
      go: master
  include:
    - os: linux
      go: go1.10rc1

script:
  - make test

services:
  - docker
