language: go
sudo: required

os:
  - linux
  - osx

go:
  - 1.8.x
  - 1.9.x
  - master

jdk:
  - openjdk8
  - openjdk9

osx_image: xcode9.1

matrix:
  allow_failures:
    - go: master
  fast_finish: true

script:
  - make ci

services:
  - docker
