language: go
sudo: required

os:
  - linux
  - osx

go:
  - 1.9.x
  - master

osx_image: xcode9.1

matrix:
  allow_failures:
    - go: master
  fast_finish: true

script:
  - make ci

services:
  - docker
